"""Task definitions for different speaking tasks."""

TASK_DEFINITIONS = {
    "1":{
      "t1": "Some people prefer to live in small towns where life is quieter. Others prefer to live in big cities with lots of activities. Which place would you prefer to live in?",
      "t2": "Read the following conversation between two people. The woman expresses her opinion about the man's problem. Talk about the dialogue. The setting of the conversation: University library, late morning. Two students are studying together. \n# The Conversation: \nFemale: Hey, you look worried. What's up? \nMale: Hi, yes a little actually. I'm really struggling with my essay for English class and I have an exam next week. \nFemale: What part are you having trouble with? \nMale: Mainly the thesis statement and how to support it with strong arguments. \nFemale: I see. How about trying brainstorming first? It is usually the first step of essay writing. \nMale: You are right. That could definitely help organize my thoughts better. I will definitely try that.   \nFemale: Or, you could also visit the writing center. They offer great feedback and can help you write your thesis. \nMale: Those are great ideas. I'll try them out. \nFemale: Glad I could help. Let's meet up later this week to review our progress. \nMale: Sounds good. Thanks a lot. \nFemale: You're welcome! We should have some coffee afterward too. \nMale: Definitely. I could use a break after all this writing. \nFemale: Agreed. Let's make it a plan."
    },    
    "2":{
      "t1": "Some people prefer to run their own private business for flexibility. Others prefer to work for a large company for benefits. Which do you think is better?",
      "t2": "Read the following conversation between two people. The woman expresses her opinion about the man's problem. Talk about the dialogue. The setting of the conversation: Cafeteria, lunchtime. Two students are having lunch. \n# The Conversation: \nFemale: Hey, you seem a bit anxious. Is everything okay? \nMale: Not really. I'm having trouble balancing my part-time job and my studies. It's getting really tiring. \nFemale: That sounds really challenging. Have you thought about talking to your manager about reducing your working hours? Sometimes, they can be flexible if they know you're a student. \nMale: I have, but I'm worried about losing money. I still need to cover my expenses, so it's a difficult decision. \nFemale: I get that. Maybe you should create a study schedule to manage your time better. That might help you stay organized and use your time effectively. \nMale: That's a good idea. A schedule might help me stay on track. I'll definitely give it a try. \nFemale: Great! It might take some time, but I'm sure you'll find a rhythm that works for you. Let's catch up next week and see how it's going. We can review your schedule together if you want. \nMale: Thanks, I appreciate the support. \nFemale: Anytime!"
    },    
    "3":{
      "t1": "Some students prefer to study during the day for better natural light. Others prefer to study at night when it is quieter. Which one do you prefer?",
      "t2": "Read the following conversation between two people. The woman expresses her opinion about the man's problem. Talk about the dialogue. The setting of the conversation: Campus bookstore, late afternoon. Two students are browsing books. \n# The Conversation: \nMale: Hi, can I join you? \nFemale: Oh hi, of course, how have you been? You look thoughtful lately.  \nMale: I’m struggling to find time to read all my books for my assignments. \nFemale: That’s tough. Have you thought about using audiobooks to save time? \nMale: I haven’t, actually that could help but I don’t have some of the audiobooks. \nFemale: Well, you could also prioritize the most important readings and read them carefully. You may just go over the others fast. \nMale: That’s a good idea. I’ll try that. \nFemale: Great! Let’s share notes to help each other out. \nMale: Thanks a lot. I appreciate it. \nFemale: Anytime!  \nMale: Maybe we can also discuss the main points together? \nFemale: Yes, that way we can ensure we cover everything essential."
    },    
    "4":{
      "t1": "Some students prefer to study with classmates to learn from each other. Others prefer to study alone for better concentration. Which do you think is better?",
      "t2": "Read the following conversation between two people. The woman expresses her opinion about the man's problem. Talk about the dialogue. The setting of the conversation: University cafeteria, lunchtime. Two students are eating together. \n# The Conversation: \nFemale: Oh hi, what’s up? Is everything OK with you? \nMale: Hi, I’m a little bit nervous these days.  \nFemale: Oh really, what’s the issue? \nMale: You know I’m trying to lose weight, but I’m really struggling with my diet lately. I just can’t find the time to eat healthy meals. \nFemale: Yes, that’s hard to find time for. Why don’t you try preparing your food on weekends? \nMale: Well, actually, that might save me time. But the problem is I’m also quite busy on weekends with my courses. \nFemale: Well, you could also carry healthy snacks with you to avoid junk food. \nMale: That’s a good idea. I’ll start doing that.  \nFemale: Great! I’m happy to help. \nMale: Thanks a lot. I appreciate it. \nFemale: Anytime!"
    },    
    "5":{
      "t1": "Some people prefer to eat at restaurants for the convenience and variety. Others prefer to prepare their own meals and eat at home for healthier options. Which one do you prefer?",
      "t2": "Read the following conversation between two people. The woman expresses her opinion about the man's problem. Talk about the dialogue. The setting of the conversation: University cafeteria, lunchtime. Two friends are eating together. \n# The Conversation: \nFemale: You look a bit down. Is everything okay? Did you get settled down? \nMale: I did, but I have a problem that I want to talk about with you. I've been feeling really isolated since I moved to this new city. I don’t know anyone here. \nFemale: That sounds tough. Have you tried joining any clubs or organizations on campus? \nMale: Not yet. Do you think it would help? \nFemale: Definitely. It's a great way to meet people with similar interests. Also, attending local events such as workshops, or cultural festivals could help you connect with the community. \nMale: Those are good ideas. I’ll give them a try. \nFemale: Anytime! Let's grab coffee next week and see how things are going. \nMale: Thanks a lot. I appreciate it. \nFemale: You're welcome! We're in this together."
    },    
    "6":{
      "t1": "Some people prefer to travel with their friends for the shared experiences and fun. Others prefer to travel on their own for freedom. Which do you think is better?",
      "t2": "Read the following conversation between two people. The woman expresses her opinion about the man's problem. Talk about the dialogue. The setting of the conversation: University cafeteria, lunchtime. Two friends are eating together. \n# The Conversation: \nMale: Hi Amber, What’s up?  \nFemale: Not bad. What about you? Have you found a job yet? \nMale: As you know, I’m struggling to find a job. It’s been so discouraging. I've been sending out resumes and attending interviews, but it seems like I miss every opportunity.  \nFemale: I know how you are feeling. Have you thought about attending job fairs? They can be a great way to meet potential employers. \nMale: I haven’t tried that yet. Do you think it would help? \nFemale: Definitely. You can also consider taking some online courses to add new skills to your resume. It can make you more attractive to employers. \nMale: Those are good suggestions. I’ll look into them. \nFemale: Anytime! Let’s meet up soon and see how things are progressing. \nMale: Thanks for the advice. I appreciate it. \nFemale: Anytime! We’ve got this."
    },    
    "7":{
      "t1": "Some students prefer to study at a university with a big campus for the diverse resources and facilities. Others prefer a small campus for easy access. Which do you think is better?",
      "t2": "Read the following conversation between two people. The woman expresses her opinion about the man's problem. Talk about the dialogue. The setting of the conversation: University cafeteria, lunchtime. Two friends are eating together. \n# The Conversation: \nFemale: You look a bit stressed, is everything OK? \nMale: I have never thought that I would have problems with my roommate. But now I’m struggling to get along with her. It’s been tense. \nFemale: Sorry to hear that. Have you thought about setting some clear rules to avoid misunderstandings? Sometimes having things in writing helps. \nMale: I haven’t tried that yet. Do you think it would help? \nFemale: Definitely. You can also consider spending more time outside of the room to give each other some space. It can help reduce tension. \nMale: Those are good suggestions. Thank you so much! \nFemale: Anytime! Let’s meet up soon and see how things are progressing. \nMale: Thanks for the advice. I appreciate it. \nFemale: Anytime! We’ve got this."
    },    
    "8":{
      "t1": "Some people prefer to watch a movie in their free time for entertainment. Others prefer to read a book for relaxation. Which activity is better?",
      "t2": "Read the following conversation between two people. The woman expresses her opinion about the man's problem. Talk about the dialogue. The setting of the conversation: University cafeteria, lunchtime. Two friends are eating together. \n# The Conversation: \nFemale: You look really tired and sleepy and you missed the first class. Is everything okay? \nMale: I’m struggling to sleep at night. I just can’t fall asleep, and it’s affecting everything. \nFemale: I see. Have you tried creating a bedtime routine to help signal to your body that it’s time to sleep? \nMale: Not really. What kind of routine? \nFemale: You could start by going to bed at the same time every night, and maybe reading a book or doing some light stretching before bed. \nMale: That might help. Do you have any other suggestions? \nFemale: You could also cut back on screen time before bed. The blue light from screens can mess with your sleep. \nMale: Those are good ideas.  \nFemale: Glad to help. Let’s catch up next week and see if it’s working. \nMale: Thanks a lot. I appreciate it. \nFemale: No problem."
    }
  } 